### ISSUE TITLE
 RelationalQueryFactory<DomainAI, AllergyIntoleranceQuery> AddValueFilter(string parameterName, ReferenceValue value), not called for ReferenceValues

### ISSUE THREAD

**Issue by bcbeatty** [FirelyTeam/Vonk.Facade.Starter#61]
I attempting to write a Firely Fascade class for Allergy Intolerance. 
When testing with this query AllergyIntolerance?patient=1474, the server/sdk isn't acting as I expect.

I created a subclass for RelationalQueryFactory<MyDomainForAI, AllergyIntoleranceQuery> following the pattern in the walkthough.
I overload this method like this
````  
    public override AllergyIntoleranceQuery AddValueFilter(string parameterName, ReferenceValue value)
        {
            if (parameterName == "patient")
            {
                return FilterByPatientId(value); 
            }
            return base.AddValueFilter(parameterName, value);
        }
````
but this method is never called, instead this method is called instead
````
  public override AllergyIntoleranceQuery Filter(string parameterName, IFilterValue value)
        {
            if (value is ReferenceValue referenceValue)
            {
                return AddValueFilter(parameterName, referenceValue);
            }         
            return base.Filter(parameterName, value);
        }
````
 

**Expected behavior**
I expect AllergyIntoleranceQuery AddValueFilter(string parameterName, ReferenceValue value) to be called not the secondary method

**Screenshots**

**Version used:**
 - FHIR Version:  R4
 - Version: 4.2.0

**Comment by frank-olthuijsen** [comment]
Hi @bcbeatty, can you check if you've added "AllergyIntolerance.patient" to "SupportedModel" > "RestrictToSearchParameters" in your Firely Server appsettings? Thank you.

**Comment by bcbeatty** [comment]
Yes, this is our SupportedModel section
"SupportedModel": {
    "RestrictToResources": [
      "Patient",     
      "AllergyIntolerance"
    ],
    "RestrictToSearchParameters": [
      "Resource._id",
      "Patient.given",
      "Patient.family",
      "Patient.gender",
      "StructureDefinition.url",
      "AllergyIntolerance.patient",
      "AllergyIntolerance.clinical-status"
    ]
  },

**Comment by mbaltus** [comment]
@bcbeatty Can you check if your administration repository has the search parameters loaded? For example with a `GET [base]/administration/SearchParameter?code=clinical-status`?
If Firely Server does not know the search parameter, it will not be able to determine that it is a reference type, and will fall back on a RawValue. You could override the AddValueFilter method with the RawValue parameter and set a breakpoint on that to see if this is the case.

**Comment by bcbeatty** [comment]
I'm not having an issue with clinical-status not being handled correctly by these methods, but with Patient.
But I do get this with the requested URL
````
{
    "resourceType": "OperationOutcome",
    "id": "c1756368-b584-4a4a-a2d4-22ca98a6e325",
    "meta": {
        "versionId": "870aaa41-961e-4bc2-a65a-d3d037f991de",
        "lastUpdated": "2021-07-19T13:49:42.0034629+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
                        "code": "5004"
                    }
                ],
                "text": "Request for not-supported ResourceType(s) SearchParameter"
            }
        }
    ]
}
````

**Comment by bcbeatty** [comment]
I'm not sure if it's because I ran the administration URI, and that refreshed a cache, but I'm now getting the expected behavior for patient, without the need to override the Filter method.

is there a precursor step I need to run when adding a new resource or parameter other than adding the SupportedModel information ?

is there detailed documentation for /administration/SearchParameter ? I'd like to add this to our integration tests

**Comment by bcbeatty** [comment]
Yes. My email is in my profile.

**Comment by frank-olthuijsen** [comment]
@bcbeatty for a regular search parameter, adding it to the SupportedModel information is sufficient. I created a solution similar to what you described and for me it worked straight away.

Information on custom searchparameters can be found here: https://docs.fire.ly/projects/Firely-Server/en/latest/features/customsearchparameters.html

**Comment by bcbeatty** [comment]
Like is said above, It may have been a caching issue or similar, when I rebooted. It acts as expected
