### ISSUE TITLE
Startup Failed: Could not load file or assembly System.Runtime 4.2.1.0

### ISSUE THREAD

**Issue by azazlhr** [FirelyTeam/Vonk.Facade.Starter#8]
As I implement Vonk FHIR Facade using the [link](http://docs.simplifier.net/vonk/facade/facade.html), I've performed all steps successfully uptil [this point](http://docs.simplifier.net/vonk/facade/debugging.html) and placed the resulting dlls in plugins directory.

Now when I start the Vonk server, it fails with following error:

> Startup Failed: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublishToken=xxxxxxxxxx' The system cannot find the file specified.

I've build my Vonk Facade project in .NET Core 2.1.

Any solution or workaround would be highly appreciated.

PS. Related [post ](https://stackoverflow.com/questions/55475219/vonk-fhir-facade-vonk-server-could-not-load-file-or-assembly-system-runtime)on SO.

**Comment by alexzautke** [comment]
Hi there!

Thanks for reaching out to us. The Vonk facade still targets netcoreapp 2.0 internally. Could you please check if the error persists if you change your development target to netcoreapp 2.0 as well?
Please note that this only concerns the development target. The facade still works as expected if you run the final build on a higher .NET Core version.

**Comment by azazlhr** [comment]
Thanks @alexzautke for a quick response.
I changed the development target to dotnet core version 2.0 and now that error is gone but now Vonk server is failed to load Microsoft.EntityFrameworkCore version 2.2.3.

I downgraded that Nuget package to version 2.0.1 to get rid of that error. After that now I'm facing following error:

> A Service of type ISearchRepository is required for RespositoryResourceResolver requires ISearchRepository. Please register it in your repository implementation. but has not (yet) been registered. Either register ISearchRepository, or make sure ISearchRepository is registered before the registeration of RepositoryResourceResolver requires ISearchRepository. Please register it in your repository implementation.

![image](https://user-images.githubusercontent.com/13200706/55466115-f966a100-5617-11e9-897a-d89b7ac00752.png)


PS. Facing same error with both the sample WiSiRepository project in this repository as well as my own exercised library.

**Comment by azazlhr** [comment]
Any findings?

**Comment by mbaltus** [comment]
The problem probably originates from the fact that an incorrect namespace is used in the PipeLineOptions of the appsettings file. Please add the "Visi.Repository" namespace to see if that helps eliminate the issue.

**Comment by azazlhr** [comment]
Thank you @mbaltus , that was spot on. 
I appreciate that.
